# Generated by Django 5.1.3 on 2025-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_item_images/'),
        ),
    ]
