# Generated by Django 5.1.3 on 2025-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_cartitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
