# Generated by Django 5.1.3 on 2025-01-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_cartitems_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='image',
        ),
    ]
