# Generated by Django 5.1.3 on 2025-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_remove_cartitems_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField()),
                ('city', models.CharField(default='Lagos', max_length=100)),
                ('state', models.CharField(default='Lagos', max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
