# Generated by Django 5.1.3 on 2025-02-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_remove_order_payment_status_order_pending_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pending_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=50),
        ),
    ]
