# Generated by Django 5.1.3 on 2025-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_order_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(default='Standard order, no customization allowed'),
        ),
    ]
