# Generated by Django 5.1.3 on 2025-02-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_order_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
