# Generated by Django 5.1.3 on 2025-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_alter_order_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
