# Generated by Django 5.1.3 on 2025-02-21 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_order_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
