# Generated by Django 5.1.3 on 2025-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_alter_order_transaction_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
