# Generated by Django 5.1.3 on 2025-02-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0018_order_text_alter_order_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pending_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
