# Generated by Django 5.1.3 on 2025-04-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0027_alter_order_owner_alter_order_pending_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
